name: Unit Test 2

on:
  push:
    branches:
      - main
      - development
      - testing-files

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Run unit test for API fetch and smoke test
      run: |
        npm install && npm run build && npm test